const ethnicityOptions = [
    'African American',
    'Asian',
    'Hispanic or Latino',
    'White',
    'Native American',
    'Pacific Islander',
    'Other',
    'Prefer not to say',
    'Multiracial',
    'Middle Eastern',
    'Indian',
    'Jewish',
    'Arab',
    'Caribbean',
    'European',
    'Mediterranean',
    'Polynesian',
    'Eurasian',
    'Indigenous Australian',
    'Maori',
    'Inuit',
    'First Nations',
    'Aboriginal',
    'Siberian',
    'Romani',
    'Berber',
    'Mestizo',
    'Criollo',
    'Zambian',
    'Creole',
    'Garifuna',
    'Cajun',
    'Gullah',
    'Afro-Latino',
    'Afro-Caribbean',
    'Afro-European',
    'Afro-Asian',
    'Afro-Indigenous',
    'Afro-Arab',
    'Afro-Brazilian',
    'Afro-Cuban',
    'Afro-Dominican',
    'Afro-Haitian',
    'Afro-Panamanian',
    'Afro-Peruvian',
    'Afro-Trinidadian',
    'Afro-Venezuelan',
    'Afro-Colombian',
    'Afro-Ecuadorian',
    'Afro-Guatemalan',
    'Afro-Honduran',
    'Afro-Mexican',
    'Afro-Nicaraguan',
    'Afro-Puerto Rican',
    'Afro-Uruguayan',
    'Afro-Argentinian',
    'Afro-Chilean',
    'Afro-Paraguayan',
    'Afro-Bolivian',
    'Afro-Guyanese',
    'Afro-Surinamese',
    'Afro-Guyanese',
    'Afro-Surinamese',
    'Afro-Jamaican',
    'Afro-Bahamian',
    'Afro-Tobagonian',
    'Afro-Belizean',
    'Afro-Costa Rican',
    'Afro-El Salvadoran',
    'Afro-Guatemalan',
    'Afro-Honduran',
    'Afro-Mexican',
    'Afro-Nicaraguan',
    'Afro-Panamanian',
    'Afro-Puerto Rican',
    'Afro-Costa Rican',
    'Afro-El Salvadoran',
    'Afro-Guatemalan',
    'Afro-Honduran',
    'Afro-Mexican',
    'Afro-Nicaraguan',
    'Afro-Panamanian',
    'Afro-Puerto Rican',
    'Afro-Caribbean Canadian',
    'Afro-Latin American Canadian',
    'Afro-Asian Canadian',
    'Afro-European Canadian',
    'Afro-Indigenous Canadian',
    'Afro-Middle Eastern Canadian',
    'Afro-Jewish Canadian',
    'Afro-Arab Canadian',
    'Afro-Caribbean British',
    'Afro-Latin American British',
    'Afro-Asian British',
    'Afro-European British',
    'Afro-Indigenous British',
    'Afro-Middle Eastern British',
    'Afro-Jewish British',
    'Afro-Arab British',
    'Afro-Caribbean Australian',
    'Afro-Latin American Australian',
    'Afro-Asian Australian',
    'Afro-European Australian',
    'Afro-Indigenous Australian',
    'Afro-Middle Eastern Australian',
    'Afro-Jewish Australian',
    'Afro-Arab Australian',
    'Afro-Caribbean New Zealander',
    'Afro-Latin American New Zealander',
    'Afro-Asian New Zealander',
    'Afro-European New Zealander',
    'Afro-Indigenous New Zealander',
    'Afro-Middle Eastern New Zealander',
    'Afro-Jewish New Zealander',
    'Afro-Arab New Zealander',
    // Add more ethnicity options as needed
  ];
  
  export default ethnicityOptions