const OffenceCategories = [
    "Advance fee fraud (419 scams)",
    "Armed robbery",
    "Arson",
    "Assault",
    "Bribery",
    "Burglary",
    "Corruption",
    "Cultivation",
    "Cyberbullying",
    "Deforestation",
    "Domestic violence",
    "Drug trafficking",
    "Driving under the influence of alcohol or drugs",
    "Driving without a valid license or proper documentation",
    "Embezzlement",
    "Financial fraud",
    "Forgery",
    "Hacking",
    "Homicide",
    "Identity theft",
    "Illegal dumping of hazardous waste",
    "Illegal mining",
    "Kidnapping",
    "Manslaughter",
    "Manufacture of illicit substances",
    "Minor fraud",
    "Money laundering",
    "Murder",
    "Online scams/fraud",
    "Phishing",
    "Possession",
    "Public nuisance",
    "Rape",
    "Reckless driving",
    "Speeding",
    "Treason",
    "Trespassing",
    "Theft",
    "Unauthorized access to computer systems",
    "Vandalism"
  ];
   export default OffenceCategories